---
title: "ELISA  analysis - Four parameric logistic curve"
author: "Vusi Mabasa"
date: '2022-06-24'
output: word_document
---

```{r}
library(dlookr)
library(tidyverse)
library(datasets)
library(drc)
```


Post-vaccination
```{r}
dat <- data.frame(conc=rep(c(6.25, 3.125, 1.56,0)),OD=c(0.259, 0.249, 0.142, 0.058))

model1 <- drm(OD~conc, fct = LL.4(names = c("slope","Lower","Upper","ED50")), data = dat)

plot(model1, type=c("all"),log="x",main= "Hepcidin-25 standard curve", xlab="Concentration (ng/ml)", ylab="OD (450nm)")

response <- c(0.065, 0.07, 0.08, 0.09, 0.143, 0.141 )
dosex <- ED(model1,response, type="absolute",display = F)
points(y=response, x=dosex[,1], col="red", pch=19, cex=1)
legend(0.1,0.25, legend = c("Estimated Conc"), col = "red", pch = 19, cex = 1)
```


Pre-vaccination ELISA ASSAY
```{r}
dat <- data.frame(conc=rep(c(6.25,3.125,1.56,0)),OD=c(0.2,0.08,0.025,0.014))

model1 <- drm(OD~conc, fct = LL.4(names = c("slope","Lower","Upper","ED50")), data = dat)

plot(model1, type=c("all"),log="x",main= "Hepcidin-25 standard curve", xlab="Concentration (ng/ml)", ylab="OD (450nm)")

response <- c(0.2,0.074,0.055,0.056,0.057,0.066,0.067)
dosex <- ED(model1,response, type="absolute",display = F)
points(y=response, x=dosex[,1], col="red", pch=19, cex=1)
legend(0.1,0.2, legend = c("Estimated Conc"), col = "red", pch = 19, cex = 1)
```

