---
title: "Neo"
author: "Neo"
date: "2024-08-04"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
library(pacman)
library(rio)
library(tidyverse)
library(janitor)
library(reporter)
library(kableExtra)
library(sjPlot)
library(skimr)
library(gtsummary)
```

```{r}
library(readxl)
Neo <- read_excel("C:/Users/VUSI/Downloads/Gadean1.xlsx")
View(Neo)
```



```{r}
skimr::skim(Neo)
```

```{r}
names(Neo)
```

```{r}
# pipe the raw dataset through the function clean_names(), assign result as "linelist"  
Neo2 <- Neo %>% 

    # manually re-name columns
           # NEW name             # OLD name
    rename(Coinfection       = Coinfection_Yes_No) %>% 
    
    # remove column
    dplyr::select(-Ct_Value, - `Collection date`, -Episode_0, - Column) %>% 
  
    
    # de-duplicate
    distinct()
```

```{r}
# fix incorrect values                   # old value       # new value
Neo2 <- Neo2 %>% 
  mutate(Sex = recode(Sex, "1.0" = "Male", "2.0" = "Female"), Coinfection= recode(Coinfection, "0" = "No", "1"= "Yes"), Covid_Waves = recode(Covid_Waves, "4.0" ="4th Wave", "3.0" = "3rd Wave", "2.0"= "2nd Wave", "1.0"= "1st Wave", "Inter waves"= "Inter Waves"))

Neo2
```

```{r}
Neo2$Age <- as.numeric(Neo2$Age)
Neo2$Coinfection <- as.character(Neo2$Coinfection)
Neo2$Covid_Waves <- as.factor(Neo2$Covid_Waves)
Neo2
```

```{r}
Neo1 <-  Neo2 %>% 
  
  dplyr::mutate(
    
       # create a new age category variable with only 5 strata levels
       Age_category = dplyr::case_when( 
            Age < 5 ~ "0-4",
            Age >= 5 & Age < 20 ~ "5-19",
            Age >= 20 & Age < 40  ~ "20-39", 
            Age >= 40 & Age < 70 ~ "40-69",
            Age >= 70 ~ "70+"),
       
       
       # previous step created age_cat_small var as character.
       # now convert it to factor and specify the levels.
       # Note that the NA values remain NA's and are not put in a level "unknown" for example,
       # since in the next analyses they have to be removed.
       Age_category = fct_relevel(Age_category, "0-4", "5-19","20-39", "40-69", "70+")
       )

Neo1
```

```{r}

```

```{r}
df <- subset(Neo1, select = c("Covid_Waves","Sex", "Age_category", "Coinfection","Hospital", "Age"), drop = FALSE)
df
```

```{r}
library(flextable)

```

```{r}
summary_table <- df %>%
  tbl_summary(by = Covid_Waves, 
              statistic = list(all_continuous() ~ "{mean} ({sd})",
                               all_categorical() ~ "{n} ({p}%)"),
              digits = all_continuous() ~ 1) %>%
  add_p(all_continuous() ~ "chisq.test") %>% 
  as_kable_extra()

# Print table
summary_table %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}
library(nnet)
tbl1 <-  multinom(Covid_Waves ~ Age_category+ Sex + Coinfection + Hospital+ Age, data=df) #%>%
  #tbl_regression(exponentiate = TRUE)
library(brant)


df$Covid_Waves <- ordered(df$Covid_Waves, levels= c("1st Wave", "2nd Wave","3rd Wave", "4th Wave", "Inter Waves"))
btbl1 <- MASS::polr(Covid_Waves~Age_category+ Sex + Coinfection + Hospital+ Age, data=df, Hess = TRUE)
btbl1 <- brant(tbl1)
btbl1
```

```{r}
library(sjPlot)
tab_model(tbl1, show.reflvl = T )
```


```{r}
# Option 2 for display
options(scipen = 999, digits = 5)


library(rstatix)
vee1 <- tidy(tbl1, conf.int = TRUE, conf.level = 0.95, exponentiate = F)
veee <- as_flextable(vee1)
veee
```


```{r}

```

```{r}
vee <- tbl_regression(tbl1, exponentiate = F)  %>%
  bold_labels() %>%
  modify_header(list(label ~ "**Variable**", all_stat_cols() ~ "**{level}**")) %>%
  as_gt() %>%
  gt::tab_header(
    title = gt::md("**Table 1. Covid Coinfections**"),
    subtitle = gt::md("_Highly Confidential_")
  ) %>%
  gt::tab_source_note("Data updated August 2024 by Vusi")

vee
```


```{r}
#vee1 <- as_flex_table(vee)

#vee1
```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```
